@startuml 
skinparam Shadowing true

actor " Админ" as user
boundary "Окно добавления\n   пользователя" as w1

user -> w1

boundary "Окно ошибки" as errorWindow #Red

control "Запись в базу\n      данных" as writeToDatabase #Green
control "Проверка корректности\n             данных" as checkCorrectData
control "Ввод данных" as Data
control "Открытие окна\n ошибки" as displayError
entity "База данных" as fs

w1 -d-> Data 
writeToDatabase  -d-> checkCorrectData 
checkCorrectData --> displayError
displayError --> errorWindow
w1 -d-> writeToDatabase
writeToDatabase --> fs

checkCorrectData --> fs

@enduml