@startuml
skinparam Shadowing true
actor "Сотрудник" as accountant
boundary "Личный кабинет\n   сотрудника" as mainMenuAc
boundary "Окно выбора\n    работы" as contractWindow
boundary "Окно подтверждения\n       выполнения работы" as accessContractWindow
boundary "Окно ошибки" as errorWindow #Red

control "Открытие окна\n ошибки" as errorWindowControl
control "Открытие окна\nвыбора работы" as contractWindowControl
control "Открытие окна\nподтверждения\n      работы" as accessContractWindowControl
control "Проверка корректности\n             данных" as checkCorrectData
control "Обновление базы\n         данных" as updateDatabase #Green
entity "База данных" as fs

accountant -u- mainMenuAc
accountant -- contractWindow
accountant -- accessContractWindow
mainMenuAc -l-> contractWindowControl
contractWindowControl -l-> contractWindow
contractWindow --> accessContractWindowControl
accessContractWindowControl --> accessContractWindow 
accessContractWindow --> checkCorrectData :Вводим дату\n  выполнения
updateDatabase <-r-> fs
checkCorrectData --> errorWindowControl
checkCorrectData --> updateDatabase
errorWindowControl -r-> errorWindow

@enduml