@startuml
skinparam Shadowing true
actor "Сотрудник" as employee
boundary "Личный кабинет" as personalCabinet
boundary "Профиль" as profile

control "Проверка данных профиля" as checkProfileData #Green
control "Открытие профиля" as openProfile
entity "База данных" as database

employee -r- personalCabinet
employee -- profile
personalCabinet -u-> openProfile : Нажата кнопка\n"Открыть профиль"
openProfile -u-> checkProfileData
checkProfileData <-u-> database : Запрос данных профиля
checkProfileData -r-> profile : Данные найдены

@enduml