@startuml
skinparam Shadowing true
actor "Сотрудник" as accountant
boundary "Главное меню\n   сотрудника" as mainMenuAc
boundary "Окно выбора\n    работы" as contractWindow
boundary "Окно подтверждения\n работы" as accessContractWindow
boundary "Окно ошибки" as errorWindow #Red

entity "База данных" as fs

accountant -> mainMenuAc :Нажал подтвердить\nвыполнение работы
mainMenuAc -> contractWindow ** :Отобразить
contractWindow -> accessContractWindow **:Отобразить
accessContractWindow --> accountant
accountant -> accessContractWindow : Вводит данные
accessContractWindow -> accessContractWindow : Проверка\n данных

alt Данные корректны
    accessContractWindow -> fs : Обновление базы
    fs --> accessContractWindow
    accessContractWindow --> accountant
else Данные не корректны
    accessContractWindow -> errorWindow ** : Создать
    errorWindow --> accountant
end

@enduml