@startuml
skinparam Shadowing true
actor "Представитель кафедры" as departmentRep
boundary "Личный кабинет" as personalCabinet
boundary "Окно работы" as workWindow
entity "База данных" as database

departmentRep -> personalCabinet : Нажать кнопку\nПодтвердить работу
departmentRep -> personalCabinet : Выбор работы
personalCabinet -> workWindow ** : Создать
workWindow -> database : Запрос данных о работе

alt Работа подтверждена
    departmentRep -> workWindow : Подтвердить работу, написать дату выполнения
else Работа отклонена
    departmentRep -> workWindow : Отклонить работу, написать комментарий
end

workWindow  -> database: Запись данных
database --> workWindow : Обновление данных
@enduml