@startuml
skinparam defaultFontName Liberation Serif
 
state "Окно входа" as login
state "Домашнее окно" as home
state "Выполняющиеся работы" as works
state "Готовые работы" as confirmworks
state "Добавить работу" as addwork
state "Подтвердить выполнение работы" as confirm

login : Пользователь может:
login : - ввести логин
login : - ввести пароль
login : - войти в систему
login : - выйти из системы

home : Пользователь может:
home : - перейти в окно с списком выполняющихся работ
home : - перейти в окно с списком готовых работы
home : - выйти из системы

works : Пользователь может:
works : - перейти в окно c списком дополнительных работ
works : - перейти в окно отправки работы на проверку

confirmworks : Пользователь может:
confirmworks : - перейти в окно подтверждения выполнения работы

addwork : Пользователь может:
addwork : - добавить новую работу

confirm : Пользователь может:
confirm : - подтвердить или отклонить выполнение выбранной работы

[*] -down-> login
login --> home : Нажата\nкнопка "Вход"
home --> works : Нажата кнопка\n "Выполняющиеся\n работы"
home --> confirmworks : Нажата кнопка\n "Готовые работы"
works --> addwork : Нажата\n кнопка "Добавить работу"
confirmworks --> confirm : Нажата\n кнопка "Подтвердить"

login -left-> [*] : Окно закрыто

@enduml