@startuml
skinparam defaultFontName Liberation Serif
 
state "Окно входа" as login
state "Домашнее окно" as home
state "Профиль" as profile
state "Мои дополнительные работы" as works
state "Отправить работу на проверку" as confirm

login : Пользователь может:
login : - ввести логин
login : - ввести пароль
login : - войти в систему
login : - выйти из системы

profile : Пользователь может:
profile : - просмотреть свой профиль


home : Пользователь может:
home : - просмотреть профиль
home : - просмотреть дополнительные работы
home : - выйти из системы

works : Пользователь может:
works : - просмотреть свои дополнительные работы
works : - перейти в окно отправки работы на проверку

confirm : Пользователь может:
confirm : - отправить работу на проверку

[*] -down-> login
login --> home : Нажата\nкнопка "Вход"
home --> profile : Нажата кнопка\n "Профиль"
home --> login : Нажата кнопка\n "Выйти из системы"
home --> works : Нажата кнопка \n "Мои дполнительные\n работы"
works --> confirm : Нажата кнопка\n "Отправить на проверку"
login -left-> [*] : Окно закрыто

@enduml